# Generated by Django 3.2.5 on 2021-07-18 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('details', models.TextField(max_length=5000, verbose_name='details')),
                ('day', models.DateField(default=datetime.date.today, verbose_name='date')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurant.restaurant', verbose_name='restaurant')),
            ],
            options={
                'unique_together': {('restaurant', 'day')},
            },
        ),
    ]
