# Generated by Django 3.2.5 on 2021-07-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='votes'),
        ),
    ]
