# Generated by Django 3.2.5 on 2021-07-18 10:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='selectoruser',
            managers=[
                ('objects', user.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='selectoruser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('restaurant_manager', 'Restaurant manager')], max_length=30, verbose_name='User Type'),
        ),
    ]
